name: CI

on: [push, pull_request]

jobs:
  build:
    name: CI (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        deno-version: [1.3.1]
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup deno ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: Format Lint
        if: matrix.os == 'ubuntu-latest'
        run: deno fmt --check
      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: deno lint --unstable
      - name: Test
        run: deno test
      - name: Deploy vercel
        uses: amondnet/vercel-action@v19        
        if: matrix.os == 'ubuntu-latest'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: yesoreyeram
          vercel-project-id: grafana-simple-deno-api-backend