name: ci

on: [push, pull_request]

jobs:
  build:
    name: tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.3.0
      - name: Check format
        if: matrix.os == 'ubuntu-latest'
        run: deno fmt --check
      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: deno lint --unstable